### ISSUE TITLE
Round the trade lock

### ISSUE THREAD

**Issue by vassilidev** [gergelyszabo94/csgo-trader-extension#131]
Hi

look at this : 

![image](https://user-images.githubusercontent.com/51865639/76846022-266b8e00-6840-11ea-987d-36bb0450e72f.png)

and this

![image](https://user-images.githubusercontent.com/51865639/76846062-34b9aa00-6840-11ea-9371-5b460907cb05.png)

Its more 4 day than 3 day, can u put an option or just round automaticly the day remaining ?

**Comment by gergelyszabo94** [comment]
I mean I could, but does that really make sense?
How would the rounding work?

**Comment by vassilidev** [comment]
when u say "its tradable in 3 days its mean today + 3d so, the 20, but if u look good, u can the 21

round like 0.1-0.4 = 0 change and 0.5-1 = +1 like maths

round(3.7) = 4 round(3.2) = 3 u see

**Comment by gergelyszabo94** [comment]
I think that would be pretty confusing to be honest. If you feel like this is important then feel free to make a PR with your changes. If you need guidance with the implementation details let me know.
