### ISSUE TITLE
[Question] How to get the tradable after date on other's inventory

### ISSUE THREAD

**Issue by PlanetTheCloud** [gergelyszabo94/csgo-trader-extension#357]
Hi, I was wondering how did you manage to implement the countdown timer on other profiles. As far as I know, without this extension, I cannot check when an item will be tradable if it is not in my inventory.

**Comment by gergelyszabo94** [comment]
Hi, while it's not displayed by Steam it's right there in the same response that you get from Steam if you browse an inventory without the extension.
It's the cache_expiration property that you are after.
See:
https://github.com/gergelyszabo94/csgo-trader-extension/blob/f64ed6131e534964e9a9d7054fa501cb0f14c4aa/extension/src/utils/getUserInventory.js#L94
