### ISSUE TITLE
Load all inventory floats

### ISSUE THREAD

**Issue by Andrew3019** [gergelyszabo94/csgo-trader-extension#362]
Is it possible to load the floats of every single item in the csgo inventory? It seems the floats only loads for the 25 items on the active page, excluding the items that have had their floats loaded previously.

**Comment by gergelyszabo94** [comment]
@Andrew3019 as you navigate to new pages those items are added to the queue and float values are loaded once the previous pages have loaded. Let me know if you experience something else.

**Comment by Andrew3019** [comment]
> @Andrew3019 as you navigate to new pages those items are added to the queue and float values are loaded once the previous pages have loaded. Let me know if you experience something else.

It only loads the current page. For example, if I start on page 1, and I scroll to page 5, the items on page 5 and only page 5 will begin to load after page 1 has completed loading; items on pages 2-4 will not load. I'm not sure if this is the way it's meant to be, but if so, it would be great if you could implement a feature such as a button that could add all new items to the queue.

**Comment by gergelyszabo94** [comment]
@Andrew3019  you are right, I added a performance optimazation that screws it up if you switch pages quickly (you had to be on the page for at elast half a second for it to be added to the queue)

**Comment by gergelyszabo94** [comment]
I brought it down to 0.1 sec as a compromise, let's hope performance will not suffer, It will be in the next update.

**Comment by Andrew3019** [comment]
@gergelyszabo94 Thanks man! I will close this issue now.
