### ISSUE TITLE
Additional Fields for Market CSV extraction?

### ISSUE THREAD

**Issue by EarthBoundGiygas** [gergelyszabo94/csgo-trader-extension#376]
Hey, great work on this app. I really love that this finally gives me the ability to pull out market history data on my account. 

Would it be possible to make it so that there is an option to tick what boxes you would like saved on the csv file? Looking over the response for the market data when you call the URL itself used by the app, The listing ID object, which contains the data, the classid etc. 

I was looking to use your app to interface into a personal DB to manage my listing history, and I think, correct me if I am wrong that the ID and classid should be able to be identifiers to link a market listing to an expiration or a sell. If you would be able to add in the option, or maybe even point me in the right direction I could attempt a PR to help myself.

**Comment by cherokee93** [comment]
+1
 I'd also like to have full date of market sales/buys field, since it's incomplete (I think it is like February 02 now)

**Comment by gergelyszabo94** [comment]
I added the following properties to the csv from the assets object:
- appid
-contextid
- assetid
- classid
- instanceid
- unowned contextid
- unowned id
- market hash name

Like for the partner properties, these are only available for sales and purchases, not for listing creation/removal.

I could not find any data for the full data so I can't add that.

I am closing it now, if you find the transactions somewhere let me know.
