### ISSUE TITLE
[FEATURE REQUET] Next.js csgotrader.app site

### ISSUE THREAD

**Issue by Hexiro** [gergelyszabo94/csgo-trader-extension#396]
If you haven't heard of [Next.js](https://nextjs.org), here's a quote from their main page

"Next.js gives you the best developer experience with all the features you need for production: hybrid static & server rendering, TypeScript support, smart bundling, route pre-fetching, and more. No config needed."

One of the main reasons I'd suggest Next.js is because you can host it for free on the [vercel](https://vercel.com) platform. Next.js is made by Vercel, so that's what it's optimized for. I don't know what your current hosting situation is like, but I can't recommend Next.js enough, and it should be nearly plug and play.

Also, Vercel can automatically deploy when you push to GitHub.
![image](https://user-images.githubusercontent.com/42787085/131051117-cb6c60cd-c141-4c48-87aa-371276c7e0a0.png)
![image](https://user-images.githubusercontent.com/42787085/131051072-6c9e28f2-f9e8-413c-9785-5d4c242595d2.png)

**Comment by gergelyszabo94** [comment]
It's hosted from an S3 bucket behind CloudFront, the cost is close to zero. There is also one-click build and deploy via CodeBuild (both the site and extension). I don't think it's worth spending time on this part of the project for now to be honest.

**Comment by Hexiro** [comment]
alright cool! I'm not sure how the auto-deploy would work with the mono repo, but maybe it wouldn't have worked well.

**Comment by Hexiro** [comment]
closing for now
