### ISSUE TITLE
Add link to CS:GO Stash page when looking at an item on the steam market

### ISSUE THREAD

**Issue by mbhound** [gergelyszabo94/csgo-trader-extension#402]
Say you were looking at the desert hydra and wanted to see what other skins were in the collection. If there was a link to the cs:go stash page to the desert hydra it would make it easy and quick to see what other skins were in that collection as well as other useful information of the gun such as the float range and prices of different wears.

**Comment by gergelyszabo94** [comment]
I wanted to make this happen not long ago when I added linkt to the collection inside inventories.
The problem is that it would only when English is the users' Steam language.
To make it work for all languages we would have to gather a mapping of all the collections names for all languages.
It's a lot of manual work.

**Comment by gergelyszabo94** [comment]
Thanks for replying, it made me realize that I kind of misunderstood the request. A simple link to the csgostash page of the item should not be a problem. I thought he wants a link to the collection, which is problematic.

**Comment by gergelyszabo94** [comment]
Do you guys know if they have a link structure where the market hash name is enough?
Because they have an id in the links and the name is also not the full name.
Example: https://csgostash.com/skin/1469/AK-47-Leet-Museo

**Comment by gergelyszabo94** [comment]
I also contacted csgostash about this.

**Comment by gergelyszabo94** [comment]
They replied and said that they added this functionality so we can simply use the market hash name now.
Examples:
https://csgostash.com/markethash/Stockholm%202021%20Contenders%20Sticker%20Capsule
https://csgostash.com/markethash/★%20StatTrak™%20Bowie%20Knife%20%7C%20Gamma%20Doppler%20%28Factory%20New%29
https://csgostash.com/markethash/Sticker%20%7C%20Crown%20%28Foil%29
