### ISSUE TITLE
select all active listing on market page

### ISSUE THREAD

**Issue by KittenOnCatnip** [gergelyszabo94/csgo-trader-extension#406]
On market homepage need the ability to select all check-boxes on active listings without instantly removing the listing. Also would be good if you could select and remove all active listings on specific item pages as well.

**Comment by gergelyszabo94** [comment]
If I understand you correctly these features are already present.
![image](https://user-images.githubusercontent.com/3636827/155159941-a7d4673a-7d3e-4cc0-a53b-b4750dd1327b.png)

**Comment by KittenOnCatnip** [comment]
need a checkbox next to the remove button that selects all checkboxes for the listings
