### ISSUE TITLE
Idea | Can you add the ability to change the CSGOFloat api url?

### ISSUE THREAD

**Issue by Tankonyako** [gergelyszabo94/csgo-trader-extension#418]
Is it possible to add changes to the domain or link pattern to view fleets. For example, csgofloat has their application on github to host their service for checking fleets.
For example, I have one of these, and sometimes csgo float goes into the request limit when you are actively checking items or very slowly it does because of the load.
https://github.com/gergelyszabo94/csgo-trader-extension/blob/f309cf66d8f7fd9ffe33b838193d479b236f9fdf/extension/src/backgroundScripts/messaging.js#L73

**Comment by gergelyszabo94** [comment]
I am not planning to add this, anyone who can host their own float endpoint can just change extension source and use the extension in developer mode. If you want help with this I can give you a short guide. Also I very rarely if ever experience issues with float loading (I don't usre it for market sniping though), only for inventories and trades.
