### ISSUE TITLE
background color

### ISSUE THREAD

**Issue by gisachi** [gergelyszabo94/csgo-trader-extension#439]
chage background contrast of Consumer Grade items and/or float item it is the same grey color and is hard to read.

**Comment by gergelyszabo94** [comment]
It's been fixed in https://github.com/gergelyszabo94/csgo-trader-extension/commit/5022f00f8b7592405fb5ee758e64defc76ee07a1
![image](https://user-images.githubusercontent.com/3636827/176561006-2b5e9456-e2ba-405b-a2e6-4c47a02e999e.png)
