### ISSUE TITLE
Feature: Link to an item on csgofloat

### ISSUE THREAD

**Issue by GODrums** [gergelyszabo94/csgo-trader-extension#446]
A very useful feature I had been missing in the past is the ability to find the corresponding csgofloat entry to an item in an inventory. Often times this can prove useful to find the previous owners (e.g. for contacting or history checks). 

I would imagine this being a link to the csgofloat database with the float / paint parameters and (possibly) stickers set. A fitting place for such a link/button could be in the technical information, which are already provided by csgofloat anyways.
![Screenshot_221](https://user-images.githubusercontent.com/21990230/185248389-b5ddc1fa-11c4-4257-ba24-4ad91ad05da9.png)

<sub>As I am not sure how active your development is: I could self-assign this feature request, but it would take some time</sub>

**Comment by gergelyszabo94** [comment]
Yeah, this could be done, I can see that the float db serach uses query params so it should be easy.

**Comment by GODrums** [comment]
Thanks for the fast response.
Yes, exactly. In my experience a search with the basic technical data should be sufficient to narrow the query result down.

So something like this:
```
function getCsgofloatLink(item) {
   const csgofloat_url = `https://csgofloat.com/db?name=${item.name}&defIndex=${item.id}&paintIndex=${item.paintindex}&paintSeed=${item.paintseed}&category=${item.category}&min=${item.float_min}&max=${item.float_max}`;
   return (
      <div>
         <a href=${csgofloat_url} target="_blank">Find on csgofloat.com</a>
      </div>
   );
}
```
