### ISSUE TITLE
Can you export market history with current Asset Id?

### ISSUE THREAD

**Issue by feeops** [gergelyszabo94/csgo-trader-extension#447]
After trade,Asset Id will change.

The export market history csv file has old Asset Id.It is not same as the one in the stock.

I want to get the cost of current Asset Id.

Can you help me?

**Comment by gergelyszabo94** [comment]
These are the properties of an asset in the market history:
![image](https://user-images.githubusercontent.com/3636827/189345120-ca0f8d5f-c0de-405b-8c87-e04b9941785c.png)
I believe the only id that is not included in the market history export is the "rollback_new_id". Is that what you need?
