### ISSUE TITLE
Can I use steam api key get market history items with price which it costs?

### ISSUE THREAD

**Issue by feeops** [gergelyszabo94/csgo-trader-extension#448]
Can I use steam api key get market history items with price which it costs?

I use this api

https://api.steampowered.com/IEconService/GetTradeHistory/v1/

But It does not have cost price.

**Comment by gergelyszabo94** [comment]
No, but there are endpoints for market prices that you can use without authentication:
https://stackoverflow.com/questions/26170185/steam-market-api
