### ISSUE TITLE
Bug: every item in own is shown twice

### ISSUE THREAD

**Issue by Samsu-F** [gergelyszabo94/csgo-trader-extension#449]
![bug_twice](https://user-images.githubusercontent.com/92742829/189481516-581d73e7-30a7-4b1c-b002-747f79bf7dec.jpg)

Every item in my inventory is shown twice. I dont know if this is caused specifically by my account or if this happens to everyone's own inventory.
I am using Mozilla Firefox 103.0.2 and the latest version of csgo trader (2.15.1).
I disabled every extension apart from csgo trader and the problem still remains.

In case this is only caused by my account, here is the link to my inventory: https://steamcommunity.com/id/CaptainSamsu/inventory/

**Comment by gergelyszabo94** [comment]
Hi, turn this off:
Options -> Inventory -> Use alternative CS:GO inventory endpoint

**Comment by Samsu-F** [comment]
Thank you!
