### ISSUE TITLE
steam API requests

### ISSUE THREAD

**Issue by tomassator** [gergelyszabo94/csgo-trader-extension#462]
A few days ago, when I use the steam extension, it gives me an error indicating that too many requests were made to the server and the market is blocked for a few hours. Could you verify the number of transactions you are currently sending each time the page is updated?
![Captura de pantalla 2022-10-30 025016](https://user-images.githubusercontent.com/69409433/198864560-466bf1c8-a733-4c51-812b-5121a417cf22.png)

**Comment by gergelyszabo94** [comment]
@tomassator  
Are we talking about the market home page?
https://steamcommunity.com/market/

**Comment by tomassator** [comment]
> @tomassator  
> Are we talking about the market home page?
> https://steamcommunity.com/market/

No, the market home page works fine. The problem is when I want to see a particular article, I get that error message. Occurs for all items

**Comment by gergelyszabo94** [comment]
@tomassator 
Hmm, that is actually weirder because there should not be a whole lot of excess requests to Steam because of the extension.
How many listings per page do you set the extension to load? (Option -> Market -> Listings per page).
Chrome update is unlikely (altough can't be rulled out). What version are of the extension/chrome are you on?
The last extension update introduced a new market feature, perhaps you could try turning that off?
(Option -> Market -> Show years on market graphs)

**Comment by tomassator** [comment]
> @tomassator 
> Hmm, that is actually weirder because there should not be a whole lot of excess requests to Steam because of the extension.
> How many listings per page do you set the extension to load? (Option -> Market -> Listings per page).
> Chrome update is unlikely (altough can't be rulled out). What version are of the extension/chrome are you on?
> The last extension update introduced a new market feature, perhaps you could try turning that off?
> (Option -> Market -> Show years on market graphs)
> 
> 

I put you in context.
I am using the extension together with selenium to automate some purchases, two/three days ago I had to update the chromedriver because chrome was updated to version 107.
Before that I had no problems with requests, in fact I was updating approximately 10 pages of different articles every 4 minutes.

With the latest version of chrome, the error just appears after about 20 page refreshes in total, so in terms of time it's 10 minutes until the error appears.

The version of chrome that I have is 107

The number of items per page that I have configured is 100, although I always had it like this

**Comment by gergelyszabo94** [comment]
I see, I updated to Chrome 107, I don't see any changes that would affect this, but again it can't be ruled out.
If you have listings per page set to 100 then that is 1 additional request every time a listings page is loaded.
Furthermore the extension starts the ItemActivityTicker which makes additional requests every few seconds (this happens without the extension too on commodity items, it only happens with the extension installed on non-commodity items).

"Reload listings on error" this option could be giving you issues, it does not make additional requests but it does reload the page when it does not load properly. Perhaps Steam is limiting you more "softly" first with errors, but the extension keeps reloading the pages with these errors.

**Comment by tomassator** [comment]
> I see, I updated to Chrome 107, I don't see any changes that would affect this, but again it can't be ruled out.
> If you have listings per page set to 100 then that is 1 additional request every time a listings page is loaded.
> Furthermore the extension starts the ItemActivityTicker which makes additional requests every few seconds (this happens without the extension too on commodity items, it only happens with the extension installed on non-commodity items).
> 
> "Reload listings on error" this option could be giving you issues, it does not make additional requests but it does reload the page when it does not load properly. Perhaps Steam is limiting you more "softly" first with errors, but the extension keeps reloading the pages with these errors.

After doing some more research and consulting with other people, apparently Steam put tighter restrictions on requests these days. Let's hope it's temporary. Thanks for your help

**Comment by nutinshell** [comment]
The issue still exists. A while ago, I disabled the plugin in Chrome because of this reason and the problem disappeared. Now, when I try to enable the plugin, the problem reappears.

**Comment by gergelyszabo94** [comment]
It's not surprising if you get limited with the extension if you have it set up to make a pretty heavy market request (100 listings).

**Comment by nutinshell** [comment]
> It's not surprising if you get limited with the extension if you have it set up to make a pretty heavy market request (100 listings).

that's pretty sad :(
