### ISSUE TITLE
Extension not work on another user inventory

### ISSUE THREAD

**Issue by ckypper** [gergelyszabo94/csgo-trader-extension#465]
Seem like Steam update their API to private. 
![image](https://user-images.githubusercontent.com/33152373/201266093-91402ee2-5cec-4c08-b45d-f753b06d07b0.png)

**Comment by gergelyszabo94** [comment]
Thanks, I fixed it in this issue: https://github.com/gergelyszabo94/csgo-trader-extension/commit/ec8ef5829c8603589216d0974a192c1e4ebf495d
