### ISSUE TITLE
Extension does not work on my own account inventory

### ISSUE THREAD

**Issue by VoicelessRoar** [gergelyszabo94/csgo-trader-extension#468]
After the recent update, it works on other peoples inventory & trade offer page but not on my own inventory.

**Comment by gergelyszabo94** [comment]
What version are you on?
What browser do you use?
Are you seeing any errors?
What exactly does not work that you expect to?

**Comment by VoicelessRoar** [comment]
2.15.5
Firefox
Most of the time the extension doesn't show the data like floats prices...
