### ISSUE TITLE
Extension randomly opens profile link

### ISSUE THREAD

**Issue by Art-em1s** [gergelyszabo94/csgo-trader-extension#469]
Haven't been able to determine at what duration this happens at, but at random time periods the extension seems to open a new tab to my profile without any interaction/input from myself.

**Comment by gergelyszabo94** [comment]
This is part of the mechanism of checking when the user is logged out that I added. A month or two ago something has changed on Steam's end which caused false positives, notications being sent out when you had "Notify about being logged out of Steam" or "Notify about being logged out of Steam on Discord" enabled. I adjusted the code so it only notifies on the second 401, on the first one it opens your profile (to get a new session? I am not sure what the mechanism is but it worked on my end). 

It sounds like this feature misbehaving for you.
Just to clarify, do you have any of those option enabled? 
How often does it happen?
Are you logged into Steam when your profile opens?
And most importantly does the page stay open for you? (it supposed to close right away).

**Comment by Art-em1s** [comment]
Looks like I did have it on:
![image](https://user-images.githubusercontent.com/7710411/203656706-d1faef1e-1bd9-41f7-9120-d6bdb386cf50.png)

Turned it off now.

Browser tab never closed for me, reported happening to other traders too (that I asked).

In my case using browser Version 1.45.131  Chromium: 107.0.5304.110 (Official Build)  (64-bit)

**Comment by gergelyszabo94** [comment]
Thanks, I will check why that could be the case.
