### ISSUE TITLE
Display tradehold time on other player inventory

### ISSUE THREAD

**Issue by ckypper** [gergelyszabo94/csgo-trader-extension#471]
This API provide this field for trade hold time: https://steamcommunity.com/inventory/76561199076427179/730/2
![image](https://user-images.githubusercontent.com/33152373/203815015-e2f9ea89-04fe-464a-be1c-94cffc0db89f.png)

**Comment by ckypper** [comment]
Closed due to v2.15.5 does not call steam inventory API on other player inventory

**Comment by gergelyszabo94** [comment]
Right, there is no point in calling that endpoint because those are "owner_descriptions", you can only see that info when you request your own inventory.
