### ISSUE TITLE
Inventory value is being added instead of changed

### ISSUE THREAD

**Issue by Nockkk** [gergelyszabo94/csgo-trader-extension#472]
Hello,
I am having an issue with the edge extension where the inventory value gets added to the value it had before instead of changing it. It only happens on other people's inventory and not on your own.

![Captura de ecrã 2022-12-01 112835](https://user-images.githubusercontent.com/45267399/205044479-8b8936c4-7072-4e04-9b76-89ab971920c7.png)
![Captura de ecrã 2022-12-01 112859](https://user-images.githubusercontent.com/45267399/205044482-39722427-6c00-443f-97f8-9d307abd57c6.png)

**Comment by gergelyszabo94** [comment]
Hmm, does it happen automatically or you do something that causes this?
I think you might have this enabled: Options -> Inventory -> Use alternative CS:GO inventory endpoint
I would start by disabling that if you do.

**Comment by gergelyszabo94** [comment]
Ahh, I see it now, thanks. I rarely switch to other games so I have not noticed this bug before.
