### ISSUE TITLE
While I am using CSGO-Trader extension, everything in the inventory is duplicated.

### ISSUE THREAD

**Issue by Vanilluv** [gergelyszabo94/csgo-trader-extension#475]
<img width="1209" alt="FN8DAcKiF1" src="https://user-images.githubusercontent.com/47251157/209760830-6a231ae9-af9f-436e-9212-3b2951a6ffe1.png">

**Comment by gergelyszabo94** [comment]
Hello, turn this off:
Options -> Inventory -> Use alternative CS:GO inventory endpoint

**Comment by Vanilluv** [comment]
Thanks for your reply, the issue has been resolved.
