### ISSUE TITLE
When I sell items, sometimes I can't get information on the price of changed items in the market, as shown in the figure.[Bing translator]

### ISSUE THREAD

**Issue by Vanilluv** [gergelyszabo94/csgo-trader-extension#476]
<img width="1209" alt="oSTMpsJcEM" src="https://user-images.githubusercontent.com/47251157/209784682-1268a259-d375-4309-82a2-9f6e79907b45.png">

**Comment by gergelyszabo94** [comment]
Hello, can you please clearly explain what you are trying to do, what you expect to happen and what actually happens?

**Comment by Vanilluv** [comment]
OK, I'll try to explain it.
For example, I want to sell my Outsiders (Glitter), 
![image](https://user-images.githubusercontent.com/47251157/209785895-eca066e6-0196-4ab1-92aa-983686c55ca6.png)
That's what I want to ask for, is that my network problem, or a server problem? [Bing translator]

**Comment by gergelyszabo94** [comment]
First of all Steam has thight limits on requests.
I recommend turning off "Load RealTime prices" in Options -> Inventory also for Options -> Trade Offer.
Then if you want prices to load you have to check the appropriate checkboxes:
![image](https://user-images.githubusercontent.com/3636827/209787531-981c9fc1-c7c6-49dc-ae2b-f95b507cf425.png)

**Comment by Vanilluv** [comment]
Thanks for your reply, I turned off the option as per the method above and now it looks like it works. [Bing translator]
