### ISSUE TITLE
Getting rate limited after spending some time on market.

### ISSUE THREAD

**Issue by LazySolitude** [gergelyszabo94/csgo-trader-extension#482]
Hello I had to disable the extension lately. I know the new rate limits steam implemented but I would like to know is there any possible updates coming which will make it so the extension can be run while spending time and checking items on the market. I suspect the itemordershistogram endpoint causes it for the show all buttons. I dont mind a setting as well which will make the extension slower if I can use it. Currently I click on like 3 items and I'm limited for multiple hours. 
![image](https://user-images.githubusercontent.com/106491423/220998005-0c689206-d6b2-4c7a-b171-9228a8f468b1.png)
To clarify I can use the market but I wont see the prices for any items which is what lead me to the itemordershistogram endpoint.

**Comment by gergelyszabo94** [comment]
The itemordershistogram requests are made by the page even without the extension installed.
You can avoid the itemordersactivity requests if you turn off these options:
Show "Buy and Sell Orders (cumulative)"
Recent activity on non-commmodity
