### ISSUE TITLE
NSFW filter improvement suggestion 

### ISSUE THREAD

**Issue by LazySolitude** [gergelyszabo94/csgo-trader-extension#484]
**Currently turning on the nsfw filter only removes the profile picture, the background and the artwork.
Would it be possible to expand it to a lot more?**
 
Here are the classes for the friend block and for the comments:
profile_friend_links profile_count_link_preview_ctn responsive_groupfriends_element
commentthread_comment_avatar playerAvatar it can be either online/offline/in game

The mode **wont filter out** the following which can include sensitive content in a work environment.
Workshop Showcase can be up to five panels gif or images and be in 3 rows. (Duplicatable with points)
Guide showcase and favorite guide. The guide showcase can contain up to 8 gifs. Some of these can be duplicated with points too.
The favorite group can contain a big imagine.

Some notable things left. I put these here since it can be important information for trading but can be sensitive content in an environment regardless. 
Review Showcase can contain sensitive ascii art
Items up for trade can contain sensitive ascii art or moving backgrounds items.
Badge Collector/Achievement showcase
Game collector/Favorite game
Completionist Showcase this is only an issue if the game has achievements. 

Although the mod is great and I use it in school or in work. I feel a lot of things weren't filtered out and the mode itself in its current state wont make it safer to use it in a serious/strange environment. If I missed out any of the potentially sensitive showcases let me know or if you need more information on them.

**Comment by gergelyszabo94** [comment]
Hello, thanks for the feedback. I pretty much removed images on profile pages when nsfw filter is on just now in https://github.com/gergelyszabo94/csgo-trader-extension/commit/ea702e6c518928334fdd7e35c177b3554301bc21

I think that does the trick. Let me know otherwise.
