### ISSUE TITLE
Generate multisell link from items chosen in inventory

### ISSUE THREAD

**Issue by Wykor** [gergelyszabo94/csgo-trader-extension#488]
It would be nice to have an option to generate multisell link from items chosen in inventory, as it's often faster and more reliable than the extension listing feature, especially for really large quantities of just a few select items.

Should also be pretty easy to implement.

**Comment by gergelyszabo94** [comment]
You can already open the multi-sell page from the selected item:
![image](https://user-images.githubusercontent.com/3636827/236010015-1e7bb309-abc5-4ed1-a7d8-ad2e7f6ffa96.png)
I wanted to make a general multisell link that applies to all items, but there are too many items and Steam can't handle that.

**Comment by Wykor** [comment]
Hah I even double checked that there is no button like this already, and missed it anyway :D. That's sufficient I think, although generating one link from selected items could still prove usefull, maybe worth giving a thought given how easy the implementation should be. Thanks for pointing out the part that already exists though!

**Comment by Wykor** [comment]
To clarify when I say selected items I mean this
![image](https://user-images.githubusercontent.com/55914312/236012189-4436615c-c452-4f57-b27c-21de26b0a298.png)

**Comment by gergelyszabo94** [comment]
I see, that should not be hard, you are right.
