### ISSUE TITLE
feat request: ability to see the amount of a specific item that you own

### ISSUE THREAD

**Issue by AceLikesGhosts** [gergelyszabo94/csgo-trader-extension#491]
I am a new user swapping from SIH, and haven't seen able to find anything relating to this.

I would like a feature where when you click on a specific item, if you own duplicates, it will state how many you own. For example, say you own 10 of the same skin, when you click on one of them I would like it to display something along the lines of `Owned: 10`.

**Comment by gergelyszabo94** [comment]
It's called "duplicate count" in my extension, look for the yellow numbers on the selected item.
![image](https://github.com/gergelyszabo94/csgo-trader-extension/assets/3636827/eadfae84-b5dc-4a6a-b9cb-6522d1ed7705)
It's optional, but should be enabled by default, if you don't see it then check your options.
![image](https://github.com/gergelyszabo94/csgo-trader-extension/assets/3636827/9f57f5d2-1f3b-457f-a356-80e51d36a25b)

**Comment by AceLikesGhosts** [comment]
Just saw this, is this feature specific to only CS:GO items? It does not work for items from TF2 from what I have seen. (:

**Comment by gergelyszabo94** [comment]
Yeah, it is. The extension is for csgo trading. Some features work for other games too, but I am not aiming to support all features for all games.

**Comment by AceLikesGhosts** [comment]
alright, well thank you anyways. have a nice day (:

**Comment by micnolmad** [comment]
Is it possible to made this work for when browsing the market? Not on the /market/listings but the /market/search page. Or if that is not possible on the /market/listings.. but the search result page would be such a huge help for me..

**Comment by gergelyszabo94** [comment]
@micnolmad like you are trying to avoid purchasing duplicate items?

**Comment by micnolmad** [comment]
Yes that is exactly what I was trying to say. At the moment I have to have two tabs open one of my inv the other of the market. I then have to select the weapon in both tabs and then locate it in my inv which does take a bit of time or I have to type it. If the app could just check the inv and add a note would make it miles easier to be a collector...
