### ISSUE TITLE
For the life of me, I can't find the settings...

### ISSUE THREAD

**Issue by 343intact** [gergelyszabo94/csgo-trader-extension#502]
I installed trader yesterday and although I like some of it's functions, it interferes with my other extensions, and I'm getting market locked. Can anyone link me to the settings, where I can disable the majority of functions? Are there any settings?

**Comment by 343intact** [comment]
Installed on firefox from official addon store

**Comment by gergelyszabo94** [comment]
Hello, check out the latest FAQ entry about getting limited by Steam and tuning your settings:
https://csgotrader.app/faq/
Also it sounds like you are unable to find the options menu. Perhaps you have the icon hidden?
Check this out: https://www.howtogeek.com/699165/how-to-choose-which-extensions-appear-on-the-firefox-toolbar/

**Comment by 343intact** [comment]
> Hello, check out the latest FAQ entry about getting limited by Steam and tuning your settings: https://csgotrader.app/faq/ Also it sounds like you are unable to find the options menu. Perhaps you have the icon hidden? Check this out: https://www.howtogeek.com/699165/how-to-choose-which-extensions-appear-on-the-firefox-toolbar/

Ok, finally found it, I was just plain blind actually. And thank you for your faq!
