### ISSUE TITLE
Price scraper no longer generates csgotrader pricing

### ISSUE THREAD

**Issue by HuggableSquare** [gergelyszabo94/csgo-trader-extension#506]
The last day it seemed to have generated anything was August 6th (https://prices.csgotrader.app/2023/08/06/csgotrader.json), everything after that doesn't seem to exist.

**Comment by gergelyszabo94** [comment]
Many pricing provider endpoint broke recently and I did not have time to work around that properly so it's broken atm. I will rewrite the whole thing in JS soon and will have it up and running.
