### ISSUE TITLE
Selecting Skins in Inventory Bug

### ISSUE THREAD

**Issue by Infinitay** [gergelyszabo94/csgo-trader-extension#508]
I am clicking on them and highlighting them but it's not appearing in the table. Items only appear if I click the "select all on page" or "select all items in inventory" buttons. I am on Chrome but I also tried on v3.0.0 that I got from GitHub and built myself.
![image](https://github.com/gergelyszabo94/csgo-trader-extension/assets/6964154/5f5a4dba-4301-43d8-833f-5090fdbaff9e)

**Comment by gergelyszabo94** [comment]
Hello, I think you have another extension installed that could be interferring. What other Steam related extensions do you have installed? Can you retry with those disabled?
