### ISSUE TITLE
CSGO Trader is incorrectly showing the price of my item.

### ISSUE THREAD

**Issue by Alexcitten** [gergelyszabo94/csgo-trader-extension#509]
I trusted your Chrome extension, and submitted a trade where from CSGO Trader's perspective I am at a ~$1$ loss, I was looking at the price on your extension, but when the trade was accepted, I found I was at a $20$ loss. Your extension showed the wrong value of the item. This is a lesson to me that I definitely need to check the price of offers through Buff and Steam, but make the correct prices.
The video that shows what the extension is incorrectly showing the price of my item: https://youtu.be/ZUcaMJ-M6Ng

**Comment by gergelyszabo94** [comment]
Hello, I am sorry for your loss. You are right in both that you should doublecheck prices and that prices could have been wrong since they were not updating at the time. It's been fixed since.
