### ISSUE TITLE
Prices Wildly Incorrect / Out of Date in Latest JSON

### ISSUE THREAD

**Issue by moosemania2329** [gergelyszabo94/csgo-trader-extension#510]
Am using http://prices.csgotrader.app/latest/prices_v6.json

Case in point: 

"Sticker | ZywOo (Gold) | Paris 2023": {"steam": {"last_24h": 68.32, "last_7d": 69.53, "last_30d": 71.54, "last_90d": 74.29}, "lootfarm": 87.95, "csgotm": "50.305", "skinport": {"suggested_price": 62.31, "starting_at": 63.5}, "csgoempire": 46.95, "swapgg": 72.58, "csgoexo": null, "cstrade": null, "skinwallet": null, "buff163": {"starting_at": {"price": 48.91}, "highest_order": {"price": 47.86}}}

Buff starting and target should both be around 39, last 24h steam avg is 55.

Another one is:

"Sticker | Ninjas in Pyjamas | Katowice 2014": {"steam": {"last_24h": 0, "last_7d": 0, "last_30d": 0, "last_90d": 0}, "lootfarm": null, "csgotm": null, "skinport": {"suggested_price": 453.23, "starting_at": 485.97}, "csgoempire": 302.09, "swapgg": null, "csgoexo": null, "cstrade": null, "skinwallet": null, "buff163": {"starting_at": {"price": 387.94}, "highest_order": {"price": 294.0}}}

Here, buff should be 340.

Haven't checked how widespread this is.

**Comment by gergelyszabo94** [comment]
Hello, this endpoint is no longer updated, the extension uses a different one.

**Comment by moosemania2329** [comment]
I'm sorry for troubling you then. Could you let me know the new one, if it has been made publicly accessible?

**Comment by gergelyszabo94** [comment]
It's meant to be used by the extension only. I recommend pricempire.com for a pricing api.

**Comment by moosemania2329** [comment]
Got it. And thanks for everything, it was awesome while it lasted.
