### ISSUE TITLE
Cs2stash links are broken

### ISSUE THREAD

**Issue by LazySolitude** [gergelyszabo94/csgo-trader-extension#513]
![ScreenShot_20240125033932](https://github.com/gergelyszabo94/csgo-trader-extension/assets/106491423/fe969b91-d63a-46e0-b846-0d0afb9888c4)
Correct link: https://csgostash.com/skin/1026/Glock-18-High-Beam

**Comment by gergelyszabo94** [comment]
They did not reply in these two weeks so I reverted instead to the csgostash.com links.
