### ISSUE TITLE
Stiletto Sapphire shows up as unkown

### ISSUE THREAD

**Issue by Mik39907** [gergelyszabo94/csgo-trader-extension#518]
Used to show correctly and noticed now it shows up unkown
https://steamcommunity.com/id/fbics/inventory
last time probably was showing correct was like 1month max 2 ago

**Comment by gergelyszabo94** [comment]
Hello, you are probably using the old Firefox version. Firefox was left behind because it's not compatible with the new version of the extension, it will most likely be compatible again, but for now I recommend using other versions (Chrome or Edge).
