### ISSUE TITLE
Export market history not working

### ISSUE THREAD

**Issue by IshanAgarwal1002** [gergelyszabo94/csgo-trader-extension#520]
Due to steam market update, the trade partner is not visible anymore. Hence, getting the following error.

![image](https://github.com/user-attachments/assets/d428d273-5b81-4f49-bccf-857a6499fae6)
![image](https://github.com/user-attachments/assets/c0f5ac80-a044-49fc-bae8-3d1f0eccfdfe)

Please fix. I hope this won't take much time since some columns need to be removed.

**Comment by IshanAgarwal1002** [comment]
Thanks for fixing. Please deploy this. Really difficult for me to keep track of items manually.

**Comment by gergelyszabo94** [comment]
[build for IshanAgarwal1002.zip](https://github.com/user-attachments/files/16423776/build.for.IshanAgarwal1002.zip)
I want to do more stuff before making a release, I made a build for you with this fix included. Here, you can find instructions for installing extensions like this: https://developer.chrome.com/docs/extensions/get-started/tutorial/hello-world#load-unpacked

**Comment by IshanAgarwal1002** [comment]
Thanks a lot!!
