### ISSUE TITLE
Agent patches price don't show in the inventory view

### ISSUE THREAD

**Issue by Nockkk** [gergelyszabo94/csgo-trader-extension#521]
I was taking a look at an inventory, and when I went to check the agent that was on the inventory, I saw that the patches price wasn't shown.

As you can see in the next screenshot, I only know that the agent has a patch when I click on it, even if the filter is sticker price.
![Captura de ecrã 2024-08-10 152029](https://github.com/user-attachments/assets/e3416daf-7f20-4f4f-a680-eb24bf3c5657)

**Comment by gergelyszabo94** [comment]
Hello, can you give me a link to that inventory if it's public?

**Comment by Nockkk** [comment]
Sure, here you have it: https://steamcommunity.com/id/aitzol14/inventory/#730
