### ISSUE TITLE
I dont see prices

### ISSUE THREAD

**Issue by froggiesex** [gergelyszabo94/csgo-trader-extension#531]
I havent seen any prices on my inventory and trade offers for like week now, i think it started after armory pass update

**Comment by gergelyszabo94** [comment]
What browser do you use? What version of the extension are you running? Is it just your own inventory that is having issues? Do you have any new type of items in your inventory?

**Comment by froggiesex** [comment]
Chrome, i just reinstalled extension and it started working, i was sure i already reinstalled earlier but maybe not then 🤷‍♂️
It somehow bugged but after reinstalling it started working normally.

**Comment by froggiesex** [comment]
I have new items in my inventory too, but the problem was with all skins, i didnt see floats either. i only saw "total inventory value: 0€"

**Comment by gergelyszabo94** [comment]
So all good now?

**Comment by froggiesex** [comment]
Yep, sorry for disturbing.
