### ISSUE TITLE
Show total of listed items, current lowest

### ISSUE THREAD

**Issue by gergelyszabo94** [gergelyszabo94/csgo-trader-extension#88]
Show the total worth of all listed items on the market. Add a column showing the prices of the lowest listing for every item listed.
Idea by: https://steamcommunity.com/profiles/76561198085748819

**Comment by bladegery** [comment]
There is no code running on the market community market page at the moment. So anyone who wants to do some greenfield development can jump into this.

**Comment by gergelyszabo94** [comment]
Add functionality to mass remove items and investigate the possibility of market history data export.

**Comment by gergelyszabo94** [comment]
Market history export feature idea by: https://www.reddit.com/user/timgotpaper

**Comment by gergelyszabo94** [comment]
![image](https://user-images.githubusercontent.com/3636827/72852669-954cc080-3caf-11ea-9c1f-aaf2ac2226f5.png)
This is how it's looking.

**Comment by gergelyszabo94** [comment]
![image](https://user-images.githubusercontent.com/3636827/72881271-bd184480-3d00-11ea-8b44-b1635b6d0a31.png)

**Comment by gergelyszabo94** [comment]
https://github.com/gergelyszabo94/csgo-trader-extension/commit/1a53a561d16a899bd1f2d817487b22a15510b9e6

**Comment by gergelyszabo94** [comment]
https://github.com/gergelyszabo94/csgo-trader-extension/commit/f7812c0845d3ed3605951de787ec61751e8ba828

**Comment by gergelyszabo94** [comment]
![image](https://user-images.githubusercontent.com/3636827/73035570-daf0c100-3e48-11ea-8dda-c612198776ef.png)

**Comment by gergelyszabo94** [comment]
![image](https://user-images.githubusercontent.com/3636827/73125370-4bf9bb00-3fa6-11ea-951d-316ccbb70283.png)
