### ISSUE TITLE
Show fade percentage on market

### ISSUE THREAD

**Issue by gergelyszabo94** [gergelyszabo94/csgo-trader-extension#94]
Show fade percentage similarly how doppler phases are shown. Idea by: https://steamcommunity.com/profiles/76561198223897044

**Comment by ivenuss** [comment]
Would be nice to add a support for new fade weapons such as AWP, MP7 and MAC-10 🎉

**Comment by gergelyszabo94** [comment]
Yeah, I don't have a databse of those unfortunately.
