### ISSUE TITLE
New feature: add X items

### ISSUE THREAD

**Issue by Jason-Tam4** [gergelyszabo94/csgo-trader-extension#98]
Is there a way to add the first x (number defined by user) items to a trade instead of everything?

**Comment by gergelyszabo94** [comment]
You can add x amount of keys. If you have an idea of for a good compact UI and/or a shortcut for this then I can add it.

**Comment by Jason-Tam4** [comment]
Something like the first x items, similar to how you can type x keys, have a spot to type x items. You can't necessarily specify the item type but for people transferring a bunch of one item from an account it would be helpful. This would also work since we can search for items, and then if we can type a number to select it would select x of that item

**Comment by gergelyszabo94** [comment]
@Jason-Tam4 What do you think about ctrl+right click for selecting the item you want + a number input (same or similar to the keys one)?

**Comment by Jason-Tam4** [comment]
Yea I think that'd also work really well actually.

**Comment by gergelyszabo94** [comment]
@Jason-Tam4 this is the result:
![2019-11-25-00-27-52](https://user-images.githubusercontent.com/3636827/69503551-ebed8680-0f1a-11ea-8370-295e0eb599ed.gif)

**Comment by Jason-Tam4** [comment]
Looks perfect, can't wait to see this and #69 pushed to the extension

**Comment by gergelyszabo94** [comment]
The feature was included in https://github.com/gergelyszabo94/csgo-trader-extension/releases/tag/1.22
